# Generated by Django 5.1.7 on 2025-04-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessorios',
            name='descricao',
            field=models.TextField(verbose_name=100),
        ),
        migrations.AlterField(
            model_name='cor',
            name='nome',
            field=models.TextField(verbose_name=40),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nome',
            field=models.TextField(verbose_name=80),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessorios', models.ManyToManyField(blank=True, to='core.acessorios')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cor')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelo')),
            ],
        ),
    ]
