# Generated by Django 5.1.7 on 2025-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_acessorios_descricao_alter_cor_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='categorias',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='acessorios',
            name='descricao',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cor',
            name='nome',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nome',
            field=models.TextField(max_length=80),
        ),
    ]
